name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- JOB 1: Sécurité Ruby ---
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libpq-dev libyaml-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - name: Scan for Ruby vulnerabilities
        run: |
          bin/brakeman --no-pager
          bin/bundler-audit --update

  # --- JOB 2: Sécurité JS ---
  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libpq-dev libyaml-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - name: Scan for JS vulnerabilities
        run: bin/importmap audit

  # --- JOB 3: Style du code (Lint) ---
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libpq-dev libyaml-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - name: Lint code for consistent style
        run: bundle exec rubocop -f github

  # --- JOB 4: Tests Unitaires et Système (RSpec) ---
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential libpq-dev libvips libyaml-dev chromium-browser

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.9'
          bundler-cache: true

      - name: Setup Database
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/factur_xray_test
          RAILS_ENV: test
        run: bundle exec rails db:prepare

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/factur_xray_test
          RAILS_ENV: test
        run: bundle exec rspec